# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gg.proto',
  package='gg.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x08gg.proto\x12\x0bgg.protobuf\"C\n\x08\x46unction\x12\x0b\n\x03\x65xe\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x0e\n\x06\x65nvars\x18\x04 \x03(\t\"\xa4\x01\n\x06InFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\r\n\x05order\x18\x03 \x01(\r\x12\x0c\n\x04size\x18\x04 \x01(\x04\x12&\n\x04type\x18\x05 \x01(\x0e\x32\x18.gg.protobuf.InFile.Type\"5\n\x04Type\x12\x08\n\x04\x46ILE\x10\x00\x12\x0e\n\nEXECUTABLE\x10\x01\x12\x13\n\x0f\x44UMMY_DIRECTORY\x10\x02\"g\n\x05Thunk\x12\'\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x15.gg.protobuf.Function\x12$\n\x07infiles\x18\x02 \x03(\x0b\x32\x13.gg.protobuf.InFile\x12\x0f\n\x07outfile\x18\x03 \x01(\t\">\n\x0cLambdaInFile\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x12\n\nexecutable\x18\x02 \x01(\x08\"t\n\x0bLambdaEvent\x12\x12\n\nthunk_hash\x18\x01 \x01(\t\x12\x11\n\ts3_bucket\x18\x02 \x01(\t\x12*\n\x07infiles\x18\x03 \x03(\x0b\x32\x19.gg.protobuf.LambdaInFile\x12\x12\n\nthunk_data\x18\x04 \x01(\t\"i\n\x0eRemoteResponse\x12\x12\n\nthunk_hash\x18\x01 \x01(\t\x12\x13\n\x0boutput_hash\x18\x02 \x01(\t\x12\x13\n\x0boutput_size\x18\x03 \x01(\x04\x12\x19\n\x11\x65xecutable_output\x18\x04 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INFILE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='gg.protobuf.InFile.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTABLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DUMMY_DIRECTORY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=206,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_INFILE_TYPE)


_FUNCTION = _descriptor.Descriptor(
  name='Function',
  full_name='gg.protobuf.Function',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exe', full_name='gg.protobuf.Function.exe', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='gg.protobuf.Function.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='gg.protobuf.Function.hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='envars', full_name='gg.protobuf.Function.envars', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=92,
)


_INFILE = _descriptor.Descriptor(
  name='InFile',
  full_name='gg.protobuf.InFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='gg.protobuf.InFile.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='gg.protobuf.InFile.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order', full_name='gg.protobuf.InFile.order', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='gg.protobuf.InFile.size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='gg.protobuf.InFile.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INFILE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=259,
)


_THUNK = _descriptor.Descriptor(
  name='Thunk',
  full_name='gg.protobuf.Thunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='function', full_name='gg.protobuf.Thunk.function', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='infiles', full_name='gg.protobuf.Thunk.infiles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outfile', full_name='gg.protobuf.Thunk.outfile', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=364,
)


_LAMBDAINFILE = _descriptor.Descriptor(
  name='LambdaInFile',
  full_name='gg.protobuf.LambdaInFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='gg.protobuf.LambdaInFile.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='gg.protobuf.LambdaInFile.size', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executable', full_name='gg.protobuf.LambdaInFile.executable', index=2,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=428,
)


_LAMBDAEVENT = _descriptor.Descriptor(
  name='LambdaEvent',
  full_name='gg.protobuf.LambdaEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thunk_hash', full_name='gg.protobuf.LambdaEvent.thunk_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s3_bucket', full_name='gg.protobuf.LambdaEvent.s3_bucket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='infiles', full_name='gg.protobuf.LambdaEvent.infiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thunk_data', full_name='gg.protobuf.LambdaEvent.thunk_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=546,
)


_REMOTERESPONSE = _descriptor.Descriptor(
  name='RemoteResponse',
  full_name='gg.protobuf.RemoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thunk_hash', full_name='gg.protobuf.RemoteResponse.thunk_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_hash', full_name='gg.protobuf.RemoteResponse.output_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_size', full_name='gg.protobuf.RemoteResponse.output_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executable_output', full_name='gg.protobuf.RemoteResponse.executable_output', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=653,
)

_INFILE.fields_by_name['type'].enum_type = _INFILE_TYPE
_INFILE_TYPE.containing_type = _INFILE
_THUNK.fields_by_name['function'].message_type = _FUNCTION
_THUNK.fields_by_name['infiles'].message_type = _INFILE
_LAMBDAEVENT.fields_by_name['infiles'].message_type = _LAMBDAINFILE
DESCRIPTOR.message_types_by_name['Function'] = _FUNCTION
DESCRIPTOR.message_types_by_name['InFile'] = _INFILE
DESCRIPTOR.message_types_by_name['Thunk'] = _THUNK
DESCRIPTOR.message_types_by_name['LambdaInFile'] = _LAMBDAINFILE
DESCRIPTOR.message_types_by_name['LambdaEvent'] = _LAMBDAEVENT
DESCRIPTOR.message_types_by_name['RemoteResponse'] = _REMOTERESPONSE

Function = _reflection.GeneratedProtocolMessageType('Function', (_message.Message,), dict(
  DESCRIPTOR = _FUNCTION,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.Function)
  ))
_sym_db.RegisterMessage(Function)

InFile = _reflection.GeneratedProtocolMessageType('InFile', (_message.Message,), dict(
  DESCRIPTOR = _INFILE,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.InFile)
  ))
_sym_db.RegisterMessage(InFile)

Thunk = _reflection.GeneratedProtocolMessageType('Thunk', (_message.Message,), dict(
  DESCRIPTOR = _THUNK,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.Thunk)
  ))
_sym_db.RegisterMessage(Thunk)

LambdaInFile = _reflection.GeneratedProtocolMessageType('LambdaInFile', (_message.Message,), dict(
  DESCRIPTOR = _LAMBDAINFILE,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.LambdaInFile)
  ))
_sym_db.RegisterMessage(LambdaInFile)

LambdaEvent = _reflection.GeneratedProtocolMessageType('LambdaEvent', (_message.Message,), dict(
  DESCRIPTOR = _LAMBDAEVENT,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.LambdaEvent)
  ))
_sym_db.RegisterMessage(LambdaEvent)

RemoteResponse = _reflection.GeneratedProtocolMessageType('RemoteResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTERESPONSE,
  __module__ = 'gg_pb2'
  # @@protoc_insertion_point(class_scope:gg.protobuf.RemoteResponse)
  ))
_sym_db.RegisterMessage(RemoteResponse)


# @@protoc_insertion_point(module_scope)
